spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/greenhand?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: myFirstDemo
